"""Shared MegaDesk node contract: FeSpec / BeSpec and entry-point discovery."""

from megadesk_contracts.agent_errors import (
    AgentError,
    AgentRunError,
    AgentStartupError,
)
from megadesk_contracts.factory import AgentFactory, RunHandle, RunStatus
from megadesk_contracts.discovery import (
    ENTRY_POINT_GROUP,
    backends_for_frontend,
    discover_backends,
    discover_frontends,
    get_backend,
    has_backend,
    load_exec_spec,
    load_fe_spec,
)
from megadesk_contracts.exec_spec import BeSpec, FeSpec, Mode
from megadesk_contracts import frame_pump, wire
from megadesk_contracts.node_logging import configure_node_logging
from megadesk_contracts.node_runtime import (
    HEARTBEAT_INTERVAL_SEC,
    NODE_HEARTBEAT_PREFIX,
    NODE_SHUTDOWN_KEY,
    NodeRuntime,
    clear_shutdown,
    heartbeat_key,
    is_reported_node_alive,
    node_should_stop,
    pid_is_alive,
    request_shutdown,
    shutdown_key,
)
from megadesk_contracts.parameters import (
    ENV_PARAMETERS,
    PARAMETERS_FILENAME,
    coerce_parameters,
    load_parameter_names,
    normalize_parameters,
    parameters_from_env,
    parameters_to_json,
)
from megadesk_contracts.log_session import (
    attach_log_session,
    begin_log_session,
    session_log_path,
)
from megadesk_contracts.paths import (
    ENV_CANVAS_ROOT,
    ENV_LOGS_DIR,
    ENV_LOGS_ROOT,
    resolve_canvas_root,
    resolve_logs_root,
    resolve_worktree_root,
)
from megadesk_contracts.realtime import RealtimeEvent, RealtimeTransport
from megadesk_contracts.repo import (
    CloneError,
    clone_path,
    default_scope_root,
    ensure_clone,
    is_clone,
    refresh_clone,
    repo_name_from_url,
)
from megadesk_contracts.supervisor_client import (
    DEFAULT_REDIS_URL,
    ENV_FACTORY_REDIS_URL,
    HOST_PYTEST_EPHEMERAL_DB,
    HOST_PYTEST_PERSISTENT_DB,
    REDIS_DB_EPHEMERAL,
    REDIS_DB_PERSISTENT,
    SUPERVISOR_ALIVE_KEY,
    SUPERVISOR_NODE_NAME,
    SUPERVISOR_SINGLETON_KEY,
    SupervisorClient,
    ensure_supervisor_running,
    redis_url_db,
    redis_url_with_db,
    redis_connect,
    resolve_ephemeral_db,
    resolve_factory_redis_url,
    resolve_persistent_db,
    resolve_redis_pair,
    resolve_redis_url,
)
from megadesk_contracts.redis_lane import (
    AGENT_LANE_EPHEMERAL_DBS,
    LANE_LEASE_TTL_SEC,
    LaneBusyError,
    allocate_lane,
    refresh_lane,
    release_lane,
)

__all__ = [
    "ENTRY_POINT_GROUP",
    "AgentError",
    "AgentFactory",
    "AgentRunError",
    "AgentStartupError",
    "BeSpec",
    "CloneError",
    "FeSpec",
    "Mode",
    "RealtimeEvent",
    "RealtimeTransport",
    "RunHandle",
    "RunStatus",
    "DEFAULT_REDIS_URL",
    "ENV_FACTORY_REDIS_URL",
    "HOST_PYTEST_EPHEMERAL_DB",
    "HOST_PYTEST_PERSISTENT_DB",
    "REDIS_DB_EPHEMERAL",
    "REDIS_DB_PERSISTENT",
    "AGENT_LANE_EPHEMERAL_DBS",
    "LANE_LEASE_TTL_SEC",
    "LaneBusyError",
    "SUPERVISOR_ALIVE_KEY",
    "SUPERVISOR_NODE_NAME",
    "SUPERVISOR_SINGLETON_KEY",
    "SupervisorClient",
    "backends_for_frontend",
    "attach_log_session",
    "begin_log_session",
    "clear_shutdown",
    "clone_path",
    "coerce_parameters",
    "configure_node_logging",
    "default_scope_root",
    "discover_backends",
    "discover_frontends",
    "ensure_clone",
    "ensure_supervisor_running",
    "frame_pump",
    "get_backend",
    "has_backend",
    "heartbeat_key",
    "is_clone",
    "is_reported_node_alive",
    "load_exec_spec",
    "load_fe_spec",
    "load_parameter_names",
    "node_should_stop",
    "normalize_parameters",
    "parameters_from_env",
    "parameters_to_json",
    "pid_is_alive",
    "refresh_clone",
    "repo_name_from_url",
    "request_shutdown",
    "resolve_canvas_root",
    "resolve_logs_root",
    "resolve_worktree_root",
    "allocate_lane",
    "redis_connect",
    "redis_url_db",
    "redis_url_with_db",
    "refresh_lane",
    "release_lane",
    "resolve_ephemeral_db",
    "resolve_factory_redis_url",
    "resolve_persistent_db",
    "resolve_redis_pair",
    "resolve_redis_url",
    "session_log_path",
    "shutdown_key",
    "wire",
    "ENV_CANVAS_ROOT",
    "ENV_LOGS_DIR",
    "ENV_LOGS_ROOT",
    "ENV_PARAMETERS",
    "PARAMETERS_FILENAME",
    "HEARTBEAT_INTERVAL_SEC",
    "NODE_HEARTBEAT_PREFIX",
    "NODE_SHUTDOWN_KEY",
    "NodeRuntime",
]
